# Use lightweight JDK 17
FROM eclipse-temurin:17-jdk-alpine

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Make Maven wrapper executable
RUN chmod +x mvnw

# Build the project
RUN ./mvnw clean package -DskipTests

# Expose port (Render will override $PORT)
ENV PORT=8081
EXPOSE 8081

# Run the built JAR (use exact name)
CMD ["java", "-jar", "target/Musify-0.0.1-SNAPSHOT.jar"]
